fix loadflow an security-analysis on merging view (#232)
regression from upgrade to powsybl 4.6

com.powsybl.commons.PowsyblException: Several NetworkFactoryService implementations found ([Default, NetworkStore]), you must add configuration in PlatformConfig's module "network" to select the implementation
        at com.powsybl.commons.config.PlatformConfigNamedProvider$Finder.find(PlatformConfigNamedProvider.java:186) ~[powsybl-commons-4.7.0.jar:na]
        at com.powsybl.commons.config.PlatformConfigNamedProvider$Finder.find(PlatformConfigNamedProvider.java:150) ~[powsybl-commons-4.7.0.jar:na]
        at com.powsybl.commons.config.PlatformConfigNamedProvider$Finder.find(PlatformConfigNamedProvider.java:89) ~[powsybl-commons-4.7.0.jar:na]
        at com.powsybl.iidm.network.NetworkFactory.find(NetworkFactory.java:34) ~[powsybl-iidm-api-4.7.0.jar:na]
        at com.powsybl.iidm.network.NetworkFactory.findDefault(NetworkFactory.java:46) ~[powsybl-iidm-api-4.7.0.jar:na]
        at com.powsybl.iidm.mergingview.MergingView.create(MergingView.java:171) ~[powsybl-iidm-mergingview-4.7.0.jar:na]
        at org.gridsuite.loadflow.server.LoadFlowService.loadFlow(LoadFlowService.java:107) ~[classes/:na]
        at org.gridsuite.loadflow.server.LoadFlowController.loadFlow(LoadFlowController.java:61) ~[classes/:na]

Signed-off-by: HARPER Jon <jon.harper87@gmail.com>