Fix azure deployment, regression from 4ec9c88ad96ee4f
error: merging from generator &{0xc001e17650 {  map[] map[]} {{ common-application-configmap  {[] [application.yml=common-application.yml] [] } <nil>}}}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"common-application-configmap", Namespace:""} exists; behavior must be merge or replace